FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/* \
    && rm -f /etc/nginx/nginx.conf \
    && rm -f /etc/nginx/conf.d/default.conf

COPY ./frontend/index.html /usr/share/nginx/html/index.html
COPY ./frontend/styles.css /usr/share/nginx/html/styles.css
COPY ./frontend/script.js /usr/share/nginx/html/script.js

COPY ./nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
