// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductCatalog.Infrastructure.Persistence;

#nullable disable

namespace ProductCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb059a77-e12c-4182-b798-872b77c28ea5"),
                            Name = "Еда"
                        },
                        new
                        {
                            Id = new Guid("7739170d-02d3-463c-9c61-22e66eed1323"),
                            Name = "Вкусности"
                        },
                        new
                        {
                            Id = new Guid("39cc7d9d-656f-44cd-b2af-a6b65bd694ea"),
                            Name = "Вода"
                        },
                        new
                        {
                            Id = new Guid("f04987ea-6f6e-4d30-9628-eb5be4cee7e9"),
                            Name = "Фрукты/овощи"
                        },
                        new
                        {
                            Id = new Guid("3d0634fe-52ac-488d-a8ba-1257376c0965"),
                            Name = "Специи"
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SpecialNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f0ab2ae-2167-4069-96c1-97c98af3cfae"),
                            CategoryId = new Guid("bb059a77-e12c-4182-b798-872b77c28ea5"),
                            Description = "Селедка соленая",
                            Name = "Селедка",
                            Note = "Акция",
                            Price = 10.0m,
                            SpecialNote = "Пересоленая"
                        },
                        new
                        {
                            Id = new Guid("ef9bcabc-9bc5-4405-a675-31c29d249e1a"),
                            CategoryId = new Guid("bb059a77-e12c-4182-b798-872b77c28ea5"),
                            Description = "Тушенка говяжья",
                            Name = "Тушенка",
                            Note = "Вкусная",
                            Price = 20.0m,
                            SpecialNote = "Жилы"
                        },
                        new
                        {
                            Id = new Guid("446a3a36-4ac8-475f-9694-983a4c67e55b"),
                            CategoryId = new Guid("bb059a77-e12c-4182-b798-872b77c28ea5"),
                            Description = "Ржаной хлеб",
                            Name = "Хлеб",
                            Note = "Свежий",
                            Price = 2.5m,
                            SpecialNote = "Без консервантов"
                        },
                        new
                        {
                            Id = new Guid("58b7c28a-4fba-4d6e-bba6-8982adf3b429"),
                            CategoryId = new Guid("7739170d-02d3-463c-9c61-22e66eed1323"),
                            Description = "В банках",
                            Name = "Сгущенка",
                            Note = "С ключом",
                            Price = 30.0m,
                            SpecialNote = "Вкусная"
                        },
                        new
                        {
                            Id = new Guid("7c655000-e4a7-4bdd-8f7c-83c8c0d79711"),
                            CategoryId = new Guid("7739170d-02d3-463c-9c61-22e66eed1323"),
                            Description = "Овсяное печенье",
                            Name = "Печенье",
                            Note = "С изюмом",
                            Price = 4.5m,
                            SpecialNote = "Большое"
                        },
                        new
                        {
                            Id = new Guid("2a6a5866-1dc3-4153-aa71-fd7ed58dd8e0"),
                            CategoryId = new Guid("7739170d-02d3-463c-9c61-22e66eed1323"),
                            Description = "Фруктовый мармелад",
                            Name = "Мармелад",
                            Note = "Много вкусов",
                            Price = 2.8m,
                            SpecialNote = "Без красителей"
                        },
                        new
                        {
                            Id = new Guid("b3420a01-18ac-4cf4-ab3f-4bcf2629e94d"),
                            CategoryId = new Guid("39cc7d9d-656f-44cd-b2af-a6b65bd694ea"),
                            Description = "В бутылках",
                            Name = "Квас",
                            Note = "Вятский",
                            Price = 2.2m,
                            SpecialNote = "Теплый"
                        },
                        new
                        {
                            Id = new Guid("daab57fb-c097-4dad-93eb-de69dadf87ff"),
                            CategoryId = new Guid("39cc7d9d-656f-44cd-b2af-a6b65bd694ea"),
                            Description = "В бутылках",
                            Name = "Вода",
                            Note = "Минеральная",
                            Price = 2.0m
                        },
                        new
                        {
                            Id = new Guid("b3686849-c3b7-4f08-905e-f6bdff1d05fd"),
                            CategoryId = new Guid("39cc7d9d-656f-44cd-b2af-a6b65bd694ea"),
                            Description = "В пакетах",
                            Name = "Сок",
                            Note = "Виноградный",
                            Price = 3.5m,
                            SpecialNote = "Кислый"
                        },
                        new
                        {
                            Id = new Guid("6017d5be-fc8e-45b4-b561-f4a7ee4a5383"),
                            CategoryId = new Guid("f04987ea-6f6e-4d30-9628-eb5be4cee7e9"),
                            Description = "Голден",
                            Name = "Яблоки",
                            Note = "Большие",
                            Price = 3.8m,
                            SpecialNote = "Новая партия"
                        },
                        new
                        {
                            Id = new Guid("17159cd6-355a-4e42-952a-59145d1a1fdd"),
                            CategoryId = new Guid("f04987ea-6f6e-4d30-9628-eb5be4cee7e9"),
                            Description = "В коробках",
                            Name = "Помидоры",
                            Note = "Черри",
                            Price = 5.2m,
                            SpecialNote = "На ветке"
                        },
                        new
                        {
                            Id = new Guid("a4ee39d4-c9bc-4f8a-883f-6a8b6ecdff70"),
                            CategoryId = new Guid("f04987ea-6f6e-4d30-9628-eb5be4cee7e9"),
                            Description = "Из Бразилии",
                            Name = "Бананы",
                            Note = "Свежие",
                            Price = 2.9m,
                            SpecialNote = "Зеленые"
                        },
                        new
                        {
                            Id = new Guid("97942486-51e8-4935-80ca-2adb6d2d2c55"),
                            CategoryId = new Guid("3d0634fe-52ac-488d-a8ba-1257376c0965"),
                            Description = "Морская соль",
                            Name = "Соль",
                            Note = "Среднего помола",
                            Price = 1.5m,
                            SpecialNote = "Богата минералами"
                        },
                        new
                        {
                            Id = new Guid("c4ec5301-01b4-4249-b21e-65559689a59c"),
                            CategoryId = new Guid("3d0634fe-52ac-488d-a8ba-1257376c0965"),
                            Description = "Молотый черный перец",
                            Name = "Перец",
                            Note = "Острый",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = new Guid("67f257d8-c76d-4631-a618-5569fac0b3c5"),
                            CategoryId = new Guid("3d0634fe-52ac-488d-a8ba-1257376c0965"),
                            Description = "Молотая паприка",
                            Name = "Паприка",
                            Note = "Венгерская",
                            Price = 3.2m,
                            SpecialNote = "Сладкая"
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ac34c8c-eb1d-48c0-9cf5-92d7bacbaffc"),
                            Email = "admin@gmail.com",
                            IsBlocked = false,
                            Name = "Administrator",
                            PasswordHash = "AQAAAAIAAYagAAAAEIeQe+1xlicOfpcjYkptypRASSGGm0wwYMtJns4bunawj2LcRGPwVLUcw3wuLCZc7w==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6d259ae6-6f45-4dc7-a780-c9bb81950ee1"),
                            Email = "prouser@gmail.com",
                            IsBlocked = false,
                            Name = "Pro User",
                            PasswordHash = "AQAAAAIAAYagAAAAENbW4YvWmFhhwjSMmEsY8jagvNaJ+EIZUmkoFrgA8w04E7rqWUipj5pfNYrDxhJFMQ==",
                            Role = "ProUser"
                        },
                        new
                        {
                            Id = new Guid("f0ca277a-aac2-4e54-b246-3f7435aa9449"),
                            Email = "user@gmail.com",
                            IsBlocked = false,
                            Name = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEFj/E2JOZ1wIU25CtVZ9a1PgyswG8gYXxNfKKO28/mO8RWxzTokrbRbgWLc7tGtMlw==",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductCatalog.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
